sudo: false
language: php
php:
  - 5.6
  - 7.1

matrix:
  fast_finish: true

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install

script:
- ./vendor/bin/phpcs ./ --standard=./phpcs.config.xml